---
title: "p8105_hw2_zh2494"
author: "zhuolun"
date: "10/5/2021"
output: github_document
---

```{r,echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
library(tidyr)
library(dplyr)

```

# question 1
```{r}
trash_df = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",range = "A2:N408") %>%
  janitor::clean_names() %>% 
  na.omit(dumpster) %>%
  mutate(sports_balls = round(as.numeric(sports_balls),digits = 0))
view(trash_df)

trash_df_19 =
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",range = "A2:B14",4) %>%
  janitor::clean_names(dat = .) %>%
  na.omit(month) %>%
  mutate(Year = "2019")
view(trash_df_19)

trash_df_18 =
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",range = "A2:B14",5) %>% 
  janitor::clean_names(dat = .) %>%
  na.omit(dumpster) %>%
  mutate(Year = "2018")
view(trash_df_18)

trash_df_18_19 = 
  bind_rows(trash_df_18,trash_df_19) %>% 
  janitor::clean_names() %>%
  mutate(month = month.name[month]) %>% 
  select("year","month",everything())
view(trash_df_18_19)

```

the total precipitation in 2018 is `r sum(trash_df_18$total)`,the median number of sports balls in a dumpster in 2019 is `r median(pull(filter(trash_df,year == 2019),sports_balls))`

# question 2
```{r}
pols_month = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  mutate(mon = as.Date(mon, format = "%m/%d/%y")) %>% 
  separate(mon, c("year","month","day")) %>% 
  mutate(
    month = month.name[as.numeric(month)],
    president = ifelse(prez_gop == 1, "gop", ifelse(prez_dem == 1, "dem",0)),
    year = as.numeric(year)) %>% 
  select(-"prez_gop",-"prez_dem",-"day")
view(pols_month)

snp = 
  read_csv("./fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>% 
  mutate(
    date = as.Date(date, format = "%m/%d/%y")) %>% 
  separate(date, c("year","month","day")) %>% 
  mutate(
    month = month.name[as.numeric(month)],
    day = NULL) %>% 
  select("year","month",everything())
snp$year = as.numeric(snp$year)
snp$year = ifelse(snp$year >= 2050, snp$year - 100, snp$year)
view(snp)

unemployment = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "value") %>% 
  mutate(
    month = str_to_title(month),
    month = month.name[match(month,month.abb)]
    )
view(unemployment)

pols_month_snp =
  left_join(pols_month,snp,by = c("year","month"))

final_df = 
  left_join(pols_month_snp,unemployment,by = c("year","month"))

skimr::skim(final_df)
summary(final_df)
```

# question 3
```{r}
Baby = read_csv("data/Popular_Baby_Names.csv")
Baby = distinct(Baby)

Olivia =
  Baby %>% 
  janitor::clean_names() %>% 
  mutate(
    ethnicity = recode(ethnicity, `ASIAN AND PACI` = "asian and pacific islander",`ASIAN AND PACIFIC ISLANDER` = "asian and pacific islander",`HISPANIC` = "hispanic",`WHITE NON HISP` = "white non hispanic",`WHITE NON HISPANIC` = "white non hispanic",`BLACK NON HISPANIC` = "black non hispanic",`BLACK NON HISP` = "black non hispanic")
  ) %>% 
  filter(childs_first_name == "Olivia") %>% 
  select(-gender,-count,-childs_first_name) %>% 
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "rank")
view(Olivia)

most_name = 
  Baby %>% 
  janitor::clean_names() %>% 
  mutate(
    ethnicity = recode(ethnicity, `ASIAN AND PACI` = "asian and pacific islander",`ASIAN AND PACIFIC ISLANDER` = "asian and pacific islander",`HISPANIC` = "hispanic",`WHITE NON HISP` = "white non hispanic",`WHITE NON HISPANIC` = "white non hispanic",`BLACK NON HISPANIC` = "black non hispanic",`BLACK NON HISP` = "black non hispanic")
  ) %>% 
  filter(gender == "MALE",rank == "1") %>% 
  select(-gender,-count,-rank) %>% 
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "childs_first_name"
  )
view(most_name)

finall_plot =
  Baby %>% 
  janitor::clean_names() %>% 
  mutate(
    ethnicity = recode(ethnicity, `ASIAN AND PACI` = "asian and pacific islander",`ASIAN AND PACIFIC ISLANDER` = "asian and pacific islander",`HISPANIC` = "hispanic",`WHITE NON HISP` = "white non hispanic",`WHITE NON HISPANIC` = "white non hispanic",`BLACK NON HISPANIC` = "black non hispanic",`BLACK NON HISP` = "black non hispanic")
  ) %>%
  filter(gender == "MALE",year_of_birth == "2016",ethnicity == "white non hispanic")
view(finall_plot)

ggplot(finall_plot, aes(x = rank, y = count )) + geom_point(alpha = 0.5)
```

